import type { Decision, AnalysisResult } from './decision-engine';

// Markdown report format - mobile-friendly and universally readable
export function generateMarkdownReport(decision: Decision, results: AnalysisResult[]): string {
  const timestamp = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  let report = `# 📊 Decision Analysis Report\n\n`;
  report += `**Decision:** ${decision.name}\n\n`;
  report += `**Generated:** ${timestamp}\n\n`;
  
  if (decision.description) {
    report += `**Description:** ${decision.description}\n\n`;
  }

  report += `## 🎯 Criteria & Weights\n\n`;
  decision.criteria.forEach((criterion) => {
    const percentage = criterion.weight;
    const bars = '▓'.repeat(Math.round(percentage / 5)) + '░'.repeat(20 - Math.round(percentage / 5));
    report += `- **${criterion.name}**: ${percentage}% \`${bars}\`\n`;
  });

  report += `\n## 📋 Options Evaluated\n\n`;
  decision.options.forEach((option, idx) => {
    report += `${idx + 1}. ${option.name}\n`;
  });

  report += `\n## 🏆 Final Rankings\n\n`;
  report += `| Rank | Option | Score | Percentage | Status |\n`;
  report += `|------|--------|-------|------------|---------|\n`;
  results.forEach((result, idx) => {
    const medal = idx === 0 ? '🥇' : idx === 1 ? '🥈' : idx === 2 ? '🥉' : `#${result.rank}`;
    const status = idx === 0 ? '✅ **RECOMMENDED**' : idx === 1 ? '⚪ Runner-up' : '▫️ Alternative';
    report += `| ${medal} | **${result.optionName}** | ${result.totalScore.toFixed(2)}/10 | ${result.percentage.toFixed(1)}% | ${status} |\n`;
  });

  report += `\n## 📈 Detailed Scoring\n\n`;
  
  // Create scoring table
  report += `| Option | `;
  decision.criteria.forEach(c => report += `${c.name} | `);
  report += `**Total** |\n`;
  
  report += `|--------| `;
  decision.criteria.forEach(() => report += `------| `);
  report += `---------|\n`;
  
  results.forEach((result) => {
    report += `| **${result.optionName}** | `;
    result.scores.forEach((score) => {
      const stars = '⭐'.repeat(Math.round(score.score / 2));
      report += `${stars} ${score.score}/10 | `;
    });
    report += `**${result.totalScore.toFixed(2)}** |\n`;
  });

  report += `\n## 💡 Recommendation\n\n`;
  const topChoice = results[0];
  const runner = results[1];
  const scoreGap = topChoice.totalScore - (runner?.totalScore || 0);

  report += `### ✅ Primary Choice: ${topChoice.optionName}\n\n`;
  report += `- **Score:** ${topChoice.totalScore.toFixed(2)}/10 (${topChoice.percentage.toFixed(1)}% confidence)\n`;
  
  if (runner) {
    report += `\n### ⚪ Alternative: ${runner.optionName}\n\n`;
    report += `- **Score:** ${runner.totalScore.toFixed(2)}/10 (${runner.percentage.toFixed(1)}% confidence)\n`;
    report += `- **Score Difference:** ${scoreGap.toFixed(2)} points\n`;
  }
  
  report += `\n> **Analysis Summary:** Based on your weighted criteria analysis, **${topChoice.optionName}** best aligns with your defined priorities and requirements.\n\n`;

  report += `## 🔍 Breakdown by Option\n\n`;
  results.forEach((result) => {
    report += `### ${result.rank === 1 ? '🥇' : result.rank === 2 ? '🥈' : result.rank === 3 ? '🥉' : '📍'} ${result.optionName} (Rank #${result.rank})\n\n`;
    
    result.scores.forEach((score, idx) => {
      const weight = decision.criteria[idx]?.weight || 0;
      const weighted = (score.score * weight) / 100;
      const progressBar = '▓'.repeat(Math.round(score.score)) + '░'.repeat(10 - Math.round(score.score));
      report += `- **${score.criterionName}:** \`${progressBar}\` ${score.score.toFixed(1)}/10 (×${weight}% = ${weighted.toFixed(2)})\n`;
    });
    report += `\n**Total Weighted Score:** ${result.totalScore.toFixed(2)}/10\n\n`;
  });

  report += `---\n\n`;
  report += `*Report generated by Decision Companion on ${timestamp}*`;

  return report;
}

// Mobile-friendly text format without ASCII art
export function generateMobileReport(decision: Decision, results: AnalysisResult[]): string {
  const timestamp = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  let report = `DECISION ANALYSIS REPORT\n`;
  report += `========================\n\n`;
  report += `Generated: ${timestamp}\n`;
  report += `Decision: ${decision.name}\n\n`;
  
  if (decision.description) {
    report += `Description: ${decision.description}\n\n`;
  }

  report += `CRITERIA & WEIGHTS\n`;
  report += `------------------\n`;
  decision.criteria.forEach((criterion) => {
    report += `• ${criterion.name}: ${criterion.weight}%\n`;
  });

  report += `\nOPTIONS EVALUATED\n`;
  report += `-----------------\n`;
  decision.options.forEach((option, idx) => {
    report += `${idx + 1}. ${option.name}\n`;
  });

  report += `\nFINAL RANKINGS\n`;
  report += `--------------\n`;
  results.forEach((result) => {
    const medal = result.rank === 1 ? '🏆' : result.rank === 2 ? '🥈' : result.rank === 3 ? '🥉' : `#${result.rank}`;
    report += `${medal} ${result.optionName}\n`;
    report += `   Score: ${result.totalScore.toFixed(2)}/10 (${result.percentage.toFixed(1)}%)\n\n`;
  });

  report += `DETAILED SCORES\n`;
  report += `---------------\n`;
  results.forEach((result) => {
    report += `\n${result.optionName} (Rank #${result.rank})\n`;
    result.scores.forEach((score, idx) => {
      const weight = decision.criteria[idx]?.weight || 0;
      const weighted = (score.score * weight) / 100;
      const stars = '★'.repeat(Math.round(score.score / 2)) + '☆'.repeat(5 - Math.round(score.score / 2));
      report += `  ${score.criterionName}: ${stars} ${score.score.toFixed(1)}/10 (×${weight}% = ${weighted.toFixed(2)})\n`;
    });
    report += `  Total: ${result.totalScore.toFixed(2)}/10\n`;
  });

  const topChoice = results[0];
  const runner = results[1];
  const scoreGap = topChoice.totalScore - (runner?.totalScore || 0);

  report += `\nRECOMMENDATION\n`;
  report += `-------------\n`;
  report += `✅ PRIMARY CHOICE: ${topChoice.optionName}\n`;
  report += `   Score: ${topChoice.totalScore.toFixed(2)}/10 (${topChoice.percentage.toFixed(1)}% confidence)\n\n`;
  
  if (runner) {
    report += `⚪ RUNNER-UP: ${runner.optionName}\n`;
    report += `   Score: ${runner.totalScore.toFixed(2)}/10 (${runner.percentage.toFixed(1)}% confidence)\n`;
    report += `   Score Difference: ${scoreGap.toFixed(2)} points\n\n`;
  }
  
  report += `Based on weighted scoring analysis, "${topChoice.optionName}" aligns best with your defined criteria and priorities.\n\n`;
  report += `--- End of Report ---`;

  return report;
}

// Desktop format with ASCII art (original)
export function generateDetailedReport(decision: Decision, results: AnalysisResult[]): string {
  const timestamp = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  let report = `╔═══════════════════════════════════════════════════════════════════════════════╗
║                         DECISION ANALYSIS REPORT                              ║
╚═══════════════════════════════════════════════════════════════════════════════╝

Generated: ${timestamp}
Decision: ${decision.name}

${decision.description ? `Description: ${decision.description}\n` : ''}

┌─────────────────────────────────────────────────────────────────────────────┐
│ CRITERIA & WEIGHTS                                                          │
└─────────────────────────────────────────────────────────────────────────────┘

`;

  decision.criteria.forEach((criterion) => {
    report += `  • ${criterion.name.padEnd(35)} ${criterion.weight}%\n`;
  });

  report += `\n┌─────────────────────────────────────────────────────────────────────────────┐
│ OPTIONS EVALUATED                                                           │
└─────────────────────────────────────────────────────────────────────────────┘

`;

  decision.options.forEach((option, idx) => {
    report += `  ${idx + 1}. ${option.name}\n`;
  });

  report += `\n┌─────────────────────────────────────────────────────────────────────────────┐
│ SCORING MATRIX                                                              │
└─────────────────────────────────────────────────────────────────────────────┘

`;

  // Build scoring table
  const colWidth = 12;
  report += `  ${'Option'.padEnd(20)}`;
  decision.criteria.forEach((c) => {
    report += c.name.substring(0, 10).padEnd(colWidth);
  });
  report += 'Total\n';
  report += '  ' + '─'.repeat(Math.max(70, 20 + decision.criteria.length * colWidth + 8)) + '\n';

  results.forEach((result) => {
    report += `  ${result.optionName.padEnd(20)}`;
    result.scores.forEach((score) => {
      report += score.score.toFixed(1).padEnd(colWidth);
    });
    report += `${result.totalScore.toFixed(2)}\n`;
  });

  report += `\n┌─────────────────────────────────────────────────────────────────────────────┐
│ WEIGHTED SCORES                                                             │
└─────────────────────────────────────────────────────────────────────────────┘

`;

  results.forEach((result) => {
    report += `  ${result.optionName.padEnd(30)} ${result.totalScore.toFixed(2)}/10 (${result.percentage.toFixed(1)}%)\n`;
  });

  report += `\n┌─────────────────────────────────────────────────────────────────────────────┐
│ FINAL RANKINGS                                                              │
└─────────────────────────────────────────────────────────────────────────────┘

`;

  results.forEach((result) => {
    const medal = result.rank === 1 ? '🥇' : result.rank === 2 ? '🥈' : result.rank === 3 ? '🥉' : '  ';
    report += `  ${medal} #${result.rank.toString().padEnd(3)} ${result.optionName.padEnd(30)} ${result.totalScore.toFixed(2)}/10\n`;
  });

  report += `\n┌─────────────────────────────────────────────────────────────────────────────┐
│ RECOMMENDATION                                                              │
└─────────────────────────────────────────────────────────────────────────────┘

`;

  const topChoice = results[0];
  const runner = results[1];
  const scoreGap = topChoice.totalScore - (runner?.totalScore || 0);

  report += `
  PRIMARY CHOICE: ${topChoice.optionName}
  Score: ${topChoice.totalScore.toFixed(2)}/10 (${topChoice.percentage.toFixed(1)}% confidence)
  
${runner ? `
  RUNNER-UP: ${runner.optionName}
  Score: ${runner.totalScore.toFixed(2)}/10 (${runner.percentage.toFixed(1)}% confidence)
  Score Difference: ${scoreGap.toFixed(2)} points
` : ''}
  
  Based on weighted scoring analysis, "${topChoice.optionName}" is the recommended 
  choice as it best aligns with your defined criteria and priorities.

`;

  report += `\n┌─────────────────────────────────────────────────────────────────────────────┐
│ DETAILED ANALYSIS                                                           │
└─────────────────────────────────────────────────────────────────────────────┘

`;

  results.forEach((result) => {
    report += `\n${result.optionName} (Rank #${result.rank})\n`;
    report += '─'.repeat(50) + '\n';

    result.scores.forEach((score, idx) => {
      const weight = decision.criteria[idx]?.weight || 0;
      const weighted = (score.score * weight) / 100;
      const bar = '█'.repeat(Math.round(score.score / 2)) + '░'.repeat(Math.round((10 - score.score) / 2));
      report += `  ${score.criterionName.padEnd(25)} ${bar} ${score.score.toFixed(1)}/10 (×${weight}% = ${weighted.toFixed(2)})\n`;
    });

    report += `\n  Total Weighted Score: ${result.totalScore.toFixed(2)}/10\n`;
  });

  report += `\n╔═══════════════════════════════════════════════════════════════════════════════╗
║ End of Report - Decision Companion                                          ║
╚═══════════════════════════════════════════════════════════════════════════════╝
`;

  return report;
}

export function exportAsJSON(decision: Decision, results: AnalysisResult[]) {
  const data = {
    metadata: {
      exportedAt: new Date().toISOString(),
      version: '1.0',
    },
    decision: {
      name: decision.name,
      description: decision.description,
      criteria: decision.criteria,
      options: decision.options,
    },
    results,
    timestamp: new Date().toLocaleString(),
  };

  return JSON.stringify(data, null, 2);
}

export function exportAsCSV(decision: Decision, results: AnalysisResult[]) {
  let csv = 'Decision Analysis Export\n';
  csv += `Decision: ${decision.name}\n`;
  csv += `Date: ${new Date().toLocaleString()}\n\n`;

  // Criteria row
  csv += 'Option,' + decision.criteria.map((c) => `${c.name} (${c.weight}%)`).join(',') + ',Total Score,Rank\n';

  // Results rows
  results.forEach((result) => {
    const scores = result.scores.map((s) => s.score).join(',');
    csv += `${result.optionName},${scores},${result.totalScore.toFixed(2)},${result.rank}\n`;
  });

  return csv;
}

export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain') {
  const element = document.createElement('a');
  element.setAttribute('href', `data:${mimeType};charset=utf-8,${encodeURIComponent(content)}`);
  element.setAttribute('download', filename);
  element.style.display = 'none';
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}

// Enhanced PDF-ready HTML with better styling and mobile responsive design
export function generatePDFContent(decision: Decision, results: AnalysisResult[]): string {
  return `<!DOCTYPE html>
<html>
<head>
    <title>Decision Analysis Report - ${decision.name}</title>
    <style>
        body { 
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
            margin: 20px;
            line-height: 1.6;
            color: #333;
            background: #fff;
        }
        .header { 
            text-align: center; 
            margin-bottom: 40px; 
            padding: 20px;
            border-bottom: 3px solid #007acc;
        }
        .header h1 {
            color: #007acc;
            margin-bottom: 10px;
            font-size: 2.5em;
        }
        .header h2 {
            color: #333;
            font-weight: normal;
            margin-bottom: 15px;
        }
        .section { 
            margin-bottom: 35px; 
            page-break-inside: avoid;
        }
        .section h3 {
            color: #007acc;
            border-bottom: 2px solid #e0e0e0;
            padding-bottom: 8px;
            margin-bottom: 20px;
        }
        .criteria-table, .results-table { 
            width: 100%; 
            border-collapse: collapse; 
            margin: 20px 0;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            border-radius: 8px;
            overflow: hidden;
        }
        .criteria-table th, .criteria-table td, .results-table th, .results-table td { 
            border: 1px solid #e0e0e0; 
            padding: 12px 15px; 
            text-align: left; 
        }
        .criteria-table th, .results-table th { 
            background: linear-gradient(135deg, #007acc, #0056b3);
            color: white;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 0.9em;
            letter-spacing: 0.5px;
        }
        .criteria-table tr:nth-child(even), .results-table tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .winner { 
            background: linear-gradient(135deg, #28a745, #20c997) !important;
            color: white;
            font-weight: bold;
        }
        .winner td {
            color: white;
        }
        .timestamp { 
            color: #666; 
            font-size: 14px;
            font-style: italic;
        }
        .recommendation {
            background: linear-gradient(135deg, #e8f5e8, #d4edda);
            border-left: 5px solid #28a745;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
        }
        .download-info {
            background: #f8f9fa;
            border: 2px dashed #007acc;
            padding: 15px;
            text-align: center;
            margin: 20px 0;
            border-radius: 8px;
        }
        @media print {
            body { margin: 0; }
            .download-info { display: none; }
        }
        @media (max-width: 768px) {
            body { margin: 10px; }
            .header h1 { font-size: 1.8em; }
            .criteria-table, .results-table { font-size: 14px; }
            .criteria-table th, .criteria-table td, .results-table th, .results-table td {
                padding: 8px 10px;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 Decision Analysis Report</h1>
        <h2>${decision.name}</h2>
        <p class="timestamp">Generated: ${new Date().toLocaleString()}</p>
    </div>
    
    <div class="download-info">
        <p><strong>💡 Tip:</strong> Use Ctrl+P (Cmd+P on Mac) to save this as a PDF, or use your browser's print function.</p>
    </div>
    
    ${decision.description ? `<div class="section">
        <h3>Description</h3>
        <p>${decision.description}</p>
    </div>` : ''}
    
    <div class="section">
        <h3>Criteria & Weights</h3>
        <table class="criteria-table">
            <tr><th>Criterion</th><th>Weight (%)</th></tr>
            ${decision.criteria.map(c => `<tr><td>${c.name}</td><td>${c.weight}%</td></tr>`).join('')}
        </table>
    </div>
    
    <div class="section">
        <h3>🏆 Final Rankings</h3>
        <table class="results-table">
            <tr>
                <th>Rank</th><th>Option</th><th>Total Score</th><th>Percentage</th><th>Status</th>
            </tr>
            ${results.map((r, i) => `<tr ${i === 0 ? 'class="winner"' : ''}>
                <td>${r.rank === 1 ? '🥇' : r.rank === 2 ? '🥈' : r.rank === 3 ? '🥉' : r.rank}</td>
                <td>${r.optionName}</td>
                <td>${r.totalScore.toFixed(2)}/10</td>
                <td>${r.percentage.toFixed(1)}%</td>
                <td>${i === 0 ? '✅ RECOMMENDED' : i === 1 ? '⚪ RUNNER-UP' : '▫️ Alternative'}</td>
            </tr>`).join('')}
        </table>
    </div>
    
    <div class="recommendation">
        <h3>💡 Recommendation</h3>
        <p><strong>Primary Choice:</strong> ${results[0].optionName}</p>
        <p><strong>Score:</strong> ${results[0].totalScore.toFixed(2)}/10 (${results[0].percentage.toFixed(1)}% confidence)</p>
        ${results[1] ? `<p><strong>Alternative:</strong> ${results[1].optionName} with ${results[1].totalScore.toFixed(2)}/10 (difference: ${(results[0].totalScore - results[1].totalScore).toFixed(2)} points)</p>` : ''}
        <p>Based on your weighted criteria analysis, <strong>${results[0].optionName}</strong> best aligns with your priorities and requirements.</p>
    </div>
    
    <div class="section">
        <h3>Detailed Scoring</h3>
        <table class="results-table">
            <tr>
                <th>Option</th>
                ${decision.criteria.map(c => `<th>${c.name}</th>`).join('')}
                <th>Total</th>
            </tr>
            ${results.map(result => `<tr>
                <td>${result.optionName}</td>
                ${result.scores.map(s => `<td>${s.score}/10</td>`).join('')}
                <td><strong>${result.totalScore.toFixed(2)}</strong></td>
            </tr>`).join('')}
        </table>
    </div>
</body>
</html>`;
}

export function generateExcelContent(decision: Decision, results: AnalysisResult[]): string {
  // Generate Excel-compatible CSV with multiple sheets
  let excel = 'Decision Analysis Report\n';
  excel += `Decision: ${decision.name}\n`;
  excel += `Generated: ${new Date().toLocaleString()}\n\n`;
  
  // Summary Sheet
  excel += 'SUMMARY\n';
  excel += 'Rank,Option,Total Score,Percentage\n';
  results.forEach(result => {
    excel += `${result.rank},${result.optionName},${result.totalScore.toFixed(2)},${result.percentage.toFixed(1)}%\n`;
  });
  
  excel += '\n\nCRITERIA\n';
  excel += 'Criterion,Weight (%)\n';
  decision.criteria.forEach(criterion => {
    excel += `${criterion.name},${criterion.weight}\n`;
  });
  
  excel += '\n\nDETAILED SCORING\n';
  excel += 'Option,' + decision.criteria.map(c => c.name).join(',') + ',Total Score\n';
  results.forEach(result => {
    const scores = result.scores.map(s => s.score).join(',');
    excel += `${result.optionName},${scores},${result.totalScore.toFixed(2)}\n`;
  });
  
  return excel;
}

// Generate PowerPoint-ready HTML content
function generatePowerPointContent(decision: Decision, results: AnalysisResult[]): string {
  const timestamp = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  let html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${decision.name} - Decision Analysis</title>
  <style>
    @page { size: 10in 7.5in landscape; margin: 0.5in; }
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 20px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }
    .slide { background: white; padding: 40px; margin-bottom: 30px; border-radius: 12px; box-shadow: 0 10px 30px rgba(0,0,0,0.2); page-break-after: always; }
    h1 { color: #667eea; font-size: 36px; margin: 0 0 10px 0; }
    h2 { color: #764ba2; font-size: 28px; margin: 30px 0 15px 0; border-bottom: 3px solid #667eea; padding-bottom: 10px; }
    h3 { color: #555; font-size: 22px; margin: 20px 0 10px 0; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 12px; text-align: left; }
    td { padding: 10px; border-bottom: 1px solid #eee; }
    tr:hover { background: #f8f9ff; }
    .ranking { font-size: 48px; font-weight: bold; color: #667eea; text-align: center; }
    .score { font-size: 36px; font-weight: bold; color: #764ba2; }
    .winner { background: linear-gradient(135deg, #f6d365 0%, #fda085 100%); color: white; padding: 20px; border-radius: 8px; margin: 20px 0; }
    .criteria-bar { height: 24px; background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); border-radius: 4px; margin: 5px 0; }
    .footer { text-align: center; color: #999; font-size: 12px; margin-top: 30px; }
    .medal { font-size: 40px; }
    .chart-container { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin: 20px 0; }
    .chart-item { text-align: center; padding: 15px; background: #f8f9ff; border-radius: 8px; }
    @media print { body { background: none; } .slide { box-shadow: none; page-break-after: always; } }
  </style>
</head>
<body>

<!-- Slide 1: Title -->
<div class="slide">
  <h1>📊 ${decision.name}</h1>
  <p style="font-size: 18px; color: #666; margin-top: 10px;">${decision.description || ''}</p>
  <div style="margin-top: 50px; padding: 20px; background: #f8f9ff; border-radius: 8px;">
    <h3>Decision Analysis Report</h3>
    <p><strong>Generated:</strong> ${timestamp}</p>
    <p><strong>Options Evaluated:</strong> ${decision.options.length}</p>
    <p><strong>Criteria Assessed:</strong> ${decision.criteria.length}</p>
  </div>
  <div class="footer">Decision Companion System • ${new Date().getFullYear()}</div>
</div>

<!-- Slide 2: Winner -->
<div class="slide">
  <h2>🏆 Recommended Choice</h2>
  <div class="winner">
    <div class="medal" style="text-align: center; margin-bottom: 15px;">🥇</div>
    <h1 style="color: white; text-align: center; margin: 0;">${results[0].optionName}</h1>
    <div class="score" style="text-align: center; color: white; margin-top: 15px;">
      ${results[0].totalScore.toFixed(2)} / 10.00
    </div>
    <p style="text-align: center; font-size: 18px; margin-top: 10px;">
      ${results[0].percentage.toFixed(1)}% confidence score
    </p>
  </div>
  ${results[1] ? `
  <div style="padding: 15px; background: #f8f9ff; border-radius: 8px; margin-top: 20px;">
    <h3 style="margin: 0 0 10px 0;">🥈 Runner-up: ${results[1].optionName}</h3>
    <p style="margin: 0;">Score: <strong>${results[1].totalScore.toFixed(2)}</strong> / 10.00 (${results[1].percentage.toFixed(1)}%)</p>
    <p style="margin: 5px 0 0 0; color: #666;">Gap: ${(results[0].totalScore - results[1].totalScore).toFixed(2)} points</p>
  </div>` : ''}
</div>

<!-- Slide 3: Rankings -->
<div class="slide">
  <h2>📋 Complete Rankings</h2>
  <table>
    <thead>
      <tr>
        <th style="width: 60px; text-align: center;">Rank</th>
        <th>Option</th>
        <th style="width: 120px; text-align: center;">Score</th>
        <th style="width: 120px; text-align: center;">Percentage</th>
      </tr>
    </thead>
    <tbody>
      ${results.map((result, idx) => `
        <tr style="${idx === 0 ? 'font-weight: bold; background: #f6d365;' : ''}">
          <td style="text-align: center; font-size: 24px;">
            ${idx === 0 ? '🥇' : idx === 1 ? '🥈' : idx === 2 ? '🥉' : result.rank}
          </td>
          <td>${result.optionName}</td>
          <td style="text-align: center; font-size: 20px; font-weight: bold; color: #764ba2;">
            ${result.totalScore.toFixed(2)}
          </td>
          <td style="text-align: center;">${result.percentage.toFixed(1)}%</td>
        </tr>
      `).join('')}
    </tbody>
  </table>
</div>

<!-- Slide 4: Criteria Weights -->
<div class="slide">
  <h2>⚖️ Decision Criteria & Weights</h2>
  <div style="margin-top: 30px;">
    ${decision.criteria.map(criterion => `
      <div style="margin-bottom: 25px;">
        <div style="display: flex; justify-content: space-between; margin-bottom: 8px;">
          <strong style="font-size: 18px;">${criterion.name}</strong>
          <span style="font-size: 18px; color: #667eea; font-weight: bold;">${criterion.weight}%</span>
        </div>
        <div style="background: #eee; border-radius: 4px; height: 24px; overflow: hidden;">
          <div class="criteria-bar" style="width: ${criterion.weight}%;"></div>
        </div>
      </div>
    `).join('')}
  </div>
</div>

<!-- Slide 5: Detailed Breakdown -->
<div class="slide">
  <h2>🔍 Detailed Scoring Matrix</h2>
  <table>
    <thead>
      <tr>
        <th>Option</th>
        ${decision.criteria.map(c => `<th style="text-align: center;">${c.name}</th>`).join('')}
        <th style="text-align: center; background: #764ba2;">Total</th>
      </tr>
    </thead>
    <tbody>
      ${results.map((result, idx) => `
        <tr style="${idx === 0 ? 'background: #f6d365; font-weight: bold;' : ''}">
          <td><strong>${result.optionName}</strong></td>
          ${result.scores.map(score => `
            <td style="text-align: center;">${score.score.toFixed(1)}</td>
          `).join('')}
          <td style="text-align: center; font-size: 18px; font-weight: bold; color: #764ba2;">
            ${result.totalScore.toFixed(2)}
          </td>
        </tr>
      `).join('')}
    </tbody>
  </table>
</div>

<!-- Slide 6: Summary -->
<div class="slide">
  <h2>💡 Key Insights</h2>
  <div class="chart-container">
    <div class="chart-item">
      <div style="font-size: 48px; color: #667eea;">🏆</div>
      <h3 style="margin: 10px 0 5px 0;">Winner</h3>
      <p style="margin: 0; font-weight: bold;">${results[0].optionName}</p>
      <p style="margin: 5px 0 0 0; color: #666;">${results[0].totalScore.toFixed(2)}/10</p>
    </div>
    <div class="chart-item">
      <div style="font-size: 48px; color: #fda085;">📊</div>
      <h3 style="margin: 10px 0 5px 0;">Avg Score</h3>
      <p style="margin: 0; font-weight: bold;">
        ${(results.reduce((sum, r) => sum + r.totalScore, 0) / results.length).toFixed(2)}
      </p>
      <p style="margin: 5px 0 0 0; color: #666;">across ${results.length} options</p>
    </div>
    <div class="chart-item">
      <div style="font-size: 48px; color: #764ba2;">📏</div>
      <h3 style="margin: 10px 0 5px 0;">Score Range</h3>
      <p style="margin: 0; font-weight: bold;">
        ${Math.min(...results.map(r => r.totalScore)).toFixed(1)} - ${Math.max(...results.map(r => r.totalScore)).toFixed(1)}
      </p>
      <p style="margin: 5px 0 0 0; color: #666;">spread: ${(Math.max(...results.map(r => r.totalScore)) - Math.min(...results.map(r => r.totalScore))).toFixed(2)}</p>
    </div>
  </div>
  <div style="margin-top: 40px; padding: 20px; background: #f8f9ff; border-radius: 8px; border-left: 4px solid #667eea;">
    <h3 style="margin-top: 0;">📝 Recommendation Summary</h3>
    <p style="line-height: 1.6;">
      Based on your weighted criteria analysis, <strong>${results[0].optionName}</strong> scored highest with 
      <strong>${results[0].totalScore.toFixed(2)}/10</strong>, earning a ${results[0].percentage.toFixed(1)}% confidence rating. 
      This option best aligns with your defined priorities and requirements.
    </p>
  </div>
  <div class="footer" style="margin-top: 40px;">Generated by Decision Companion • ${timestamp}</div>
</div>

</body>
</html>`;

  return html;
}

// Mobile-aware export function
export function exportDecision(decision: Decision, results: AnalysisResult[], format: 'json' | 'pdf' | 'excel' | 'ppt', isMobile: boolean = false) {
  const timestamp = new Date().getTime();
  const baseName = decision.name.toLowerCase().replace(/\s+/g, '-');
  
  switch (format) {
    case 'json':
      const jsonContent = exportAsJSON(decision, results);
      downloadFile(jsonContent, `decision-data-${baseName}-${timestamp}.json`, 'application/json');
      break;
      
    case 'pdf':
      // Generate enhanced PDF-ready HTML
      const pdfContent = generatePDFContent(decision, results);
      const newWindow = window.open();
      if (newWindow) {
        newWindow.document.write(pdfContent);
        newWindow.document.close();
        // Auto-trigger print dialog for PDF save
        setTimeout(() => {
          newWindow.print();
        }, 500);
      }
      break;
      
    case 'excel':
      const excelContent = generateExcelContent(decision, results);
      downloadFile(excelContent, `decision-analysis-${baseName}-${timestamp}.csv`, 'text/csv');
      break;
      
    case 'ppt':
      // Generate PowerPoint-ready HTML
      const pptContent = generatePowerPointContent(decision, results);
      const pptWindow = window.open();
      if (pptWindow) {
        pptWindow.document.write(pptContent);
        pptWindow.document.close();
        // Auto-trigger print dialog for PDF/PPT save
        setTimeout(() => {
          pptWindow.print();
        }, 500);
      }
      break;
  }
}

// Export comparison data in multiple formats
export function exportComparison(
  decisions: any[],
  format: 'json' | 'pdf' | 'excel' | 'ppt'
) {
  const timestamp = new Date().getTime();
  const date = new Date().toISOString().slice(0, 10);
  
  switch (format) {
    case 'json':
      const jsonData = {
        timestamp: new Date().toISOString(),
        decisions: decisions
      };
      downloadFile(
        JSON.stringify(jsonData, null, 2),
        `decision-comparison-${date}.json`,
        'application/json'
      );
      break;
      
    case 'excel':
      let csv = 'Decision Name,Description,Top Choice,Top Score,Options Count,Criteria Count\n';
      decisions.forEach(d => {
        csv += `"${d.name}","${d.description}","${d.topChoice?.optionName || 'N/A'}",${d.topChoice?.totalScore?.toFixed(2) || 0},${d.optionCount},${d.criteriaCount}\n`;
      });
      downloadFile(csv, `decision-comparison-${date}.csv`, 'text/csv');
      break;
      
    case 'pdf':
    case 'ppt':
      const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Decision Comparison Report</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; background: #f5f5f5; }
    .header { text-align: center; margin-bottom: 40px; }
    h1 { color: #2563eb; }
    .decision-card { background: white; padding: 20px; margin-bottom: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
    .decision-title { font-size: 24px; font-weight: bold; color: #1e40af; margin-bottom: 10px; }
    .decision-desc { color: #666; margin-bottom: 15px; }
    .stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin-top: 15px; }
    .stat { text-align: center; padding: 10px; background: #f8f9ff; border-radius: 4px; }
    .stat-label { font-size: 12px; color: #666; }
    .stat-value { font-size: 20px; font-weight: bold; color: #2563eb; }
    .winner { background: linear-gradient(135deg, #f6d365 0%, #fda085 100%); color: white; padding: 15px; border-radius: 8px; margin-top: 10px; }
    @media print { body { background: none; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>📊 Decision Comparison Report</h1>
    <p>Generated on ${new Date().toLocaleDateString()}</p>
  </div>
  ${decisions.map((d, idx) => `
    <div class="decision-card">
      <div class="decision-title">${idx + 1}. ${d.name}</div>
      <div class="decision-desc">${d.description || 'No description'}</div>
      ${d.topChoice ? `
        <div class="winner">
          <strong>🏆 Top Choice:</strong> ${d.topChoice.optionName} 
          (Score: ${d.topChoice.totalScore?.toFixed(2)}/10)
        </div>
      ` : ''}
      <div class="stats">
        <div class="stat">
          <div class="stat-label">Options</div>
          <div class="stat-value">${d.optionCount || 0}</div>
        </div>
        <div class="stat">
          <div class="stat-label">Criteria</div>
          <div class="stat-value">${d.criteriaCount || 0}</div>
        </div>
        <div class="stat">
          <div class="stat-label">Top Score</div>
          <div class="stat-value">${d.topChoice?.totalScore?.toFixed(1) || '0'}</div>
        </div>
      </div>
    </div>
  `).join('')}
</body>
</html>`;
      
      const newWindow = window.open();
      if (newWindow) {
        newWindow.document.write(html);
        newWindow.document.close();
        setTimeout(() => newWindow.print(), 500);
      }
      break;
  }
}
