import type { Decision, AnalysisResult } from './decision-engine';

// Markdown report format - mobile-friendly and universally readable
export function generateMarkdownReport(decision: Decision, results: AnalysisResult[]): string {
  const timestamp = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  let report = `# 📊 Decision Analysis Report\n\n`;
  report += `**Decision:** ${decision.name}\n\n`;
  report += `**Generated:** ${timestamp}\n\n`;
  
  if (decision.description) {
    report += `**Description:** ${decision.description}\n\n`;
  }

  report += `## 🎯 Criteria & Weights\n\n`;
  decision.criteria.forEach((criterion) => {
    const percentage = criterion.weight;
    const bars = '▓'.repeat(Math.round(percentage / 5)) + '░'.repeat(20 - Math.round(percentage / 5));
    report += `- **${criterion.name}**: ${percentage}% \`${bars}\`\n`;
  });

  report += `\n## 📋 Options Evaluated\n\n`;
  decision.options.forEach((option, idx) => {
    report += `${idx + 1}. ${option.name}\n`;
  });

  report += `\n## 🏆 Final Rankings\n\n`;
  report += `| Rank | Option | Score | Percentage | Status |\n`;
  report += `|------|--------|-------|------------|---------|\n`;
  results.forEach((result, idx) => {
    const medal = idx === 0 ? '🥇' : idx === 1 ? '🥈' : idx === 2 ? '🥉' : `#${result.rank}`;
    const status = idx === 0 ? '✅ **RECOMMENDED**' : idx === 1 ? '⚪ Runner-up' : '▫️ Alternative';
    report += `| ${medal} | **${result.optionName}** | ${result.totalScore.toFixed(2)}/10 | ${result.percentage.toFixed(1)}% | ${status} |\n`;
  });

  report += `\n## 📈 Detailed Scoring\n\n`;
  
  // Create scoring table
  report += `| Option | `;
  decision.criteria.forEach(c => report += `${c.name} | `);
  report += `**Total** |\n`;
  
  report += `|--------| `;
  decision.criteria.forEach(() => report += `------| `);
  report += `---------|\n`;
  
  results.forEach((result) => {
    report += `| **${result.optionName}** | `;
    result.scores.forEach((score) => {
      const stars = '⭐'.repeat(Math.round(score.score / 2));
      report += `${stars} ${score.score}/10 | `;
    });
    report += `**${result.totalScore.toFixed(2)}** |\n`;
  });

  report += `\n## 💡 Recommendation\n\n`;
  const topChoice = results[0];
  const runner = results[1];
  const scoreGap = topChoice.totalScore - (runner?.totalScore || 0);

  report += `### ✅ Primary Choice: ${topChoice.optionName}\n\n`;
  report += `- **Score:** ${topChoice.totalScore.toFixed(2)}/10 (${topChoice.percentage.toFixed(1)}% confidence)\n`;
  
  if (runner) {
    report += `\n### ⚪ Alternative: ${runner.optionName}\n\n`;
    report += `- **Score:** ${runner.totalScore.toFixed(2)}/10 (${runner.percentage.toFixed(1)}% confidence)\n`;
    report += `- **Score Difference:** ${scoreGap.toFixed(2)} points\n`;
  }
  
  report += `\n> **Analysis Summary:** Based on your weighted criteria analysis, **${topChoice.optionName}** best aligns with your defined priorities and requirements.\n\n`;

  report += `## 🔍 Breakdown by Option\n\n`;
  results.forEach((result) => {
    report += `### ${result.rank === 1 ? '🥇' : result.rank === 2 ? '🥈' : result.rank === 3 ? '🥉' : '📍'} ${result.optionName} (Rank #${result.rank})\n\n`;
    
    result.scores.forEach((score, idx) => {
      const weight = decision.criteria[idx]?.weight || 0;
      const weighted = (score.score * weight) / 100;
      const progressBar = '▓'.repeat(Math.round(score.score)) + '░'.repeat(10 - Math.round(score.score));
      report += `- **${score.criterionName}:** \`${progressBar}\` ${score.score.toFixed(1)}/10 (×${weight}% = ${weighted.toFixed(2)})\n`;
    });
    report += `\n**Total Weighted Score:** ${result.totalScore.toFixed(2)}/10\n\n`;
  });

  report += `---\n\n`;
  report += `*Report generated by Decision Companion on ${timestamp}*`;

  return report;
}

// Mobile-friendly text format without ASCII art
export function generateMobileReport(decision: Decision, results: AnalysisResult[]): string {
  const timestamp = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  let report = `DECISION ANALYSIS REPORT\n`;
  report += `========================\n\n`;
  report += `Generated: ${timestamp}\n`;
  report += `Decision: ${decision.name}\n\n`;
  
  if (decision.description) {
    report += `Description: ${decision.description}\n\n`;
  }

  report += `CRITERIA & WEIGHTS\n`;
  report += `------------------\n`;
  decision.criteria.forEach((criterion) => {
    report += `• ${criterion.name}: ${criterion.weight}%\n`;
  });

  report += `\nOPTIONS EVALUATED\n`;
  report += `-----------------\n`;
  decision.options.forEach((option, idx) => {
    report += `${idx + 1}. ${option.name}\n`;
  });

  report += `\nFINAL RANKINGS\n`;
  report += `--------------\n`;
  results.forEach((result) => {
    const medal = result.rank === 1 ? '🏆' : result.rank === 2 ? '🥈' : result.rank === 3 ? '🥉' : `#${result.rank}`;
    report += `${medal} ${result.optionName}\n`;
    report += `   Score: ${result.totalScore.toFixed(2)}/10 (${result.percentage.toFixed(1)}%)\n\n`;
  });

  report += `DETAILED SCORES\n`;
  report += `---------------\n`;
  results.forEach((result) => {
    report += `\n${result.optionName} (Rank #${result.rank})\n`;
    result.scores.forEach((score, idx) => {
      const weight = decision.criteria[idx]?.weight || 0;
      const weighted = (score.score * weight) / 100;
      const stars = '★'.repeat(Math.round(score.score / 2)) + '☆'.repeat(5 - Math.round(score.score / 2));
      report += `  ${score.criterionName}: ${stars} ${score.score.toFixed(1)}/10 (×${weight}% = ${weighted.toFixed(2)})\n`;
    });
    report += `  Total: ${result.totalScore.toFixed(2)}/10\n`;
  });

  const topChoice = results[0];
  const runner = results[1];
  const scoreGap = topChoice.totalScore - (runner?.totalScore || 0);

  report += `\nRECOMMENDATION\n`;
  report += `-------------\n`;
  report += `✅ PRIMARY CHOICE: ${topChoice.optionName}\n`;
  report += `   Score: ${topChoice.totalScore.toFixed(2)}/10 (${topChoice.percentage.toFixed(1)}% confidence)\n\n`;
  
  if (runner) {
    report += `⚪ RUNNER-UP: ${runner.optionName}\n`;
    report += `   Score: ${runner.totalScore.toFixed(2)}/10 (${runner.percentage.toFixed(1)}% confidence)\n`;
    report += `   Score Difference: ${scoreGap.toFixed(2)} points\n\n`;
  }
  
  report += `Based on weighted scoring analysis, "${topChoice.optionName}" aligns best with your defined criteria and priorities.\n\n`;
  report += `--- End of Report ---`;

  return report;
}

// Desktop format with ASCII art (original)
export function generateDetailedReport(decision: Decision, results: AnalysisResult[]): string {
  const timestamp = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  let report = `╔═══════════════════════════════════════════════════════════════════════════════╗
║                         DECISION ANALYSIS REPORT                              ║
╚═══════════════════════════════════════════════════════════════════════════════╝

Generated: ${timestamp}
Decision: ${decision.name}

${decision.description ? `Description: ${decision.description}\n` : ''}

┌─────────────────────────────────────────────────────────────────────────────┐
│ CRITERIA & WEIGHTS                                                          │
└─────────────────────────────────────────────────────────────────────────────┘

`;

  decision.criteria.forEach((criterion) => {
    report += `  • ${criterion.name.padEnd(35)} ${criterion.weight}%\n`;
  });

  report += `\n┌─────────────────────────────────────────────────────────────────────────────┐
│ OPTIONS EVALUATED                                                           │
└─────────────────────────────────────────────────────────────────────────────┘

`;

  decision.options.forEach((option, idx) => {
    report += `  ${idx + 1}. ${option.name}\n`;
  });

  report += `\n┌─────────────────────────────────────────────────────────────────────────────┐
│ SCORING MATRIX                                                              │
└─────────────────────────────────────────────────────────────────────────────┘

`;

  // Build scoring table
  const colWidth = 12;
  report += `  ${'Option'.padEnd(20)}`;
  decision.criteria.forEach((c) => {
    report += c.name.substring(0, 10).padEnd(colWidth);
  });
  report += 'Total\n';
  report += '  ' + '─'.repeat(Math.max(70, 20 + decision.criteria.length * colWidth + 8)) + '\n';

  results.forEach((result) => {
    report += `  ${result.optionName.padEnd(20)}`;
    result.scores.forEach((score) => {
      report += score.score.toFixed(1).padEnd(colWidth);
    });
    report += `${result.totalScore.toFixed(2)}\n`;
  });

  report += `\n┌─────────────────────────────────────────────────────────────────────────────┐
│ WEIGHTED SCORES                                                             │
└─────────────────────────────────────────────────────────────────────────────┘

`;

  results.forEach((result) => {
    report += `  ${result.optionName.padEnd(30)} ${result.totalScore.toFixed(2)}/10 (${result.percentage.toFixed(1)}%)\n`;
  });

  report += `\n┌─────────────────────────────────────────────────────────────────────────────┐
│ FINAL RANKINGS                                                              │
└─────────────────────────────────────────────────────────────────────────────┘

`;

  results.forEach((result) => {
    const medal = result.rank === 1 ? '🥇' : result.rank === 2 ? '🥈' : result.rank === 3 ? '🥉' : '  ';
    report += `  ${medal} #${result.rank.toString().padEnd(3)} ${result.optionName.padEnd(30)} ${result.totalScore.toFixed(2)}/10\n`;
  });

  report += `\n┌─────────────────────────────────────────────────────────────────────────────┐
│ RECOMMENDATION                                                              │
└─────────────────────────────────────────────────────────────────────────────┘

`;

  const topChoice = results[0];
  const runner = results[1];
  const scoreGap = topChoice.totalScore - (runner?.totalScore || 0);

  report += `
  PRIMARY CHOICE: ${topChoice.optionName}
  Score: ${topChoice.totalScore.toFixed(2)}/10 (${topChoice.percentage.toFixed(1)}% confidence)
  
${runner ? `
  RUNNER-UP: ${runner.optionName}
  Score: ${runner.totalScore.toFixed(2)}/10 (${runner.percentage.toFixed(1)}% confidence)
  Score Difference: ${scoreGap.toFixed(2)} points
` : ''}
  
  Based on weighted scoring analysis, "${topChoice.optionName}" is the recommended 
  choice as it best aligns with your defined criteria and priorities.

`;

  report += `\n┌─────────────────────────────────────────────────────────────────────────────┐
│ DETAILED ANALYSIS                                                           │
└─────────────────────────────────────────────────────────────────────────────┘

`;

  results.forEach((result) => {
    report += `\n${result.optionName} (Rank #${result.rank})\n`;
    report += '─'.repeat(50) + '\n';

    result.scores.forEach((score, idx) => {
      const weight = decision.criteria[idx]?.weight || 0;
      const weighted = (score.score * weight) / 100;
      const bar = '█'.repeat(Math.round(score.score / 2)) + '░'.repeat(Math.round((10 - score.score) / 2));
      report += `  ${score.criterionName.padEnd(25)} ${bar} ${score.score.toFixed(1)}/10 (×${weight}% = ${weighted.toFixed(2)})\n`;
    });

    report += `\n  Total Weighted Score: ${result.totalScore.toFixed(2)}/10\n`;
  });

  report += `\n╔═══════════════════════════════════════════════════════════════════════════════╗
║ End of Report - Decision Companion                                          ║
╚═══════════════════════════════════════════════════════════════════════════════╝
`;

  return report;
}

export function exportAsJSON(decision: Decision, results: AnalysisResult[]) {
  const data = {
    metadata: {
      exportedAt: new Date().toISOString(),
      version: '1.0',
    },
    decision: {
      name: decision.name,
      description: decision.description,
      criteria: decision.criteria,
      options: decision.options,
    },
    results,
    timestamp: new Date().toLocaleString(),
  };

  return JSON.stringify(data, null, 2);
}

export function exportAsCSV(decision: Decision, results: AnalysisResult[]) {
  let csv = 'Decision Analysis Export\n';
  csv += `Decision: ${decision.name}\n`;
  csv += `Date: ${new Date().toLocaleString()}\n\n`;

  // Criteria row
  csv += 'Option,' + decision.criteria.map((c) => `${c.name} (${c.weight}%)`).join(',') + ',Total Score,Rank\n';

  // Results rows
  results.forEach((result) => {
    const scores = result.scores.map((s) => s.score).join(',');
    csv += `${result.optionName},${scores},${result.totalScore.toFixed(2)},${result.rank}\n`;
  });

  return csv;
}

export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain') {
  const element = document.createElement('a');
  element.setAttribute('href', `data:${mimeType};charset=utf-8,${encodeURIComponent(content)}`);
  element.setAttribute('download', filename);
  element.style.display = 'none';
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}

// Enhanced PDF-ready HTML with better styling and mobile responsive design
export function generatePDFContent(decision: Decision, results: AnalysisResult[]): string {
  return `<!DOCTYPE html>
<html>
<head>
    <title>Decision Analysis Report - ${decision.name}</title>
    <style>
        body { 
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
            margin: 20px;
            line-height: 1.6;
            color: #333;
            background: #fff;
        }
        .header { 
            text-align: center; 
            margin-bottom: 40px; 
            padding: 20px;
            border-bottom: 3px solid #007acc;
        }
        .header h1 {
            color: #007acc;
            margin-bottom: 10px;
            font-size: 2.5em;
        }
        .header h2 {
            color: #333;
            font-weight: normal;
            margin-bottom: 15px;
        }
        .section { 
            margin-bottom: 35px; 
            page-break-inside: avoid;
        }
        .section h3 {
            color: #007acc;
            border-bottom: 2px solid #e0e0e0;
            padding-bottom: 8px;
            margin-bottom: 20px;
        }
        .criteria-table, .results-table { 
            width: 100%; 
            border-collapse: collapse; 
            margin: 20px 0;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            border-radius: 8px;
            overflow: hidden;
        }
        .criteria-table th, .criteria-table td, .results-table th, .results-table td { 
            border: 1px solid #e0e0e0; 
            padding: 12px 15px; 
            text-align: left; 
        }
        .criteria-table th, .results-table th { 
            background: linear-gradient(135deg, #007acc, #0056b3);
            color: white;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 0.9em;
            letter-spacing: 0.5px;
        }
        .criteria-table tr:nth-child(even), .results-table tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .winner { 
            background: linear-gradient(135deg, #28a745, #20c997) !important;
            color: white;
            font-weight: bold;
        }
        .winner td {
            color: white;
        }
        .timestamp { 
            color: #666; 
            font-size: 14px;
            font-style: italic;
        }
        .recommendation {
            background: linear-gradient(135deg, #e8f5e8, #d4edda);
            border-left: 5px solid #28a745;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
        }
        .download-info {
            background: #f8f9fa;
            border: 2px dashed #007acc;
            padding: 15px;
            text-align: center;
            margin: 20px 0;
            border-radius: 8px;
        }
        @media print {
            body { margin: 0; }
            .download-info { display: none; }
        }
        @media (max-width: 768px) {
            body { margin: 10px; }
            .header h1 { font-size: 1.8em; }
            .criteria-table, .results-table { font-size: 14px; }
            .criteria-table th, .criteria-table td, .results-table th, .results-table td {
                padding: 8px 10px;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 Decision Analysis Report</h1>
        <h2>${decision.name}</h2>
        <p class="timestamp">Generated: ${new Date().toLocaleString()}</p>
    </div>
    
    <div class="download-info">
        <p><strong>💡 Tip:</strong> Use Ctrl+P (Cmd+P on Mac) to save this as a PDF, or use your browser's print function.</p>
    </div>
    
    ${decision.description ? `<div class="section">
        <h3>Description</h3>
        <p>${decision.description}</p>
    </div>` : ''}
    
    <div class="section">
        <h3>Criteria & Weights</h3>
        <table class="criteria-table">
            <tr><th>Criterion</th><th>Weight (%)</th></tr>
            ${decision.criteria.map(c => `<tr><td>${c.name}</td><td>${c.weight}%</td></tr>`).join('')}
        </table>
    </div>
    
    <div class="section">
        <h3>🏆 Final Rankings</h3>
        <table class="results-table">
            <tr>
                <th>Rank</th><th>Option</th><th>Total Score</th><th>Percentage</th><th>Status</th>
            </tr>
            ${results.map((r, i) => `<tr ${i === 0 ? 'class="winner"' : ''}>
                <td>${r.rank === 1 ? '🥇' : r.rank === 2 ? '🥈' : r.rank === 3 ? '🥉' : r.rank}</td>
                <td>${r.optionName}</td>
                <td>${r.totalScore.toFixed(2)}/10</td>
                <td>${r.percentage.toFixed(1)}%</td>
                <td>${i === 0 ? '✅ RECOMMENDED' : i === 1 ? '⚪ RUNNER-UP' : '▫️ Alternative'}</td>
            </tr>`).join('')}
        </table>
    </div>
    
    <div class="recommendation">
        <h3>💡 Recommendation</h3>
        <p><strong>Primary Choice:</strong> ${results[0].optionName}</p>
        <p><strong>Score:</strong> ${results[0].totalScore.toFixed(2)}/10 (${results[0].percentage.toFixed(1)}% confidence)</p>
        ${results[1] ? `<p><strong>Alternative:</strong> ${results[1].optionName} with ${results[1].totalScore.toFixed(2)}/10 (difference: ${(results[0].totalScore - results[1].totalScore).toFixed(2)} points)</p>` : ''}
        <p>Based on your weighted criteria analysis, <strong>${results[0].optionName}</strong> best aligns with your priorities and requirements.</p>
    </div>
    
    <div class="section">
        <h3>Detailed Scoring</h3>
        <table class="results-table">
            <tr>
                <th>Option</th>
                ${decision.criteria.map(c => `<th>${c.name}</th>`).join('')}
                <th>Total</th>
            </tr>
            ${results.map(result => `<tr>
                <td>${result.optionName}</td>
                ${result.scores.map(s => `<td>${s.score}/10</td>`).join('')}
                <td><strong>${result.totalScore.toFixed(2)}</strong></td>
            </tr>`).join('')}
        </table>
    </div>
</body>
</html>`;
}

export function generateExcelContent(decision: Decision, results: AnalysisResult[]): string {
  // Generate Excel-compatible CSV with multiple sheets
  let excel = 'Decision Analysis Report\n';
  excel += `Decision: ${decision.name}\n`;
  excel += `Generated: ${new Date().toLocaleString()}\n\n`;
  
  // Summary Sheet
  excel += 'SUMMARY\n';
  excel += 'Rank,Option,Total Score,Percentage\n';
  results.forEach(result => {
    excel += `${result.rank},${result.optionName},${result.totalScore.toFixed(2)},${result.percentage.toFixed(1)}%\n`;
  });
  
  excel += '\n\nCRITERIA\n';
  excel += 'Criterion,Weight (%)\n';
  decision.criteria.forEach(criterion => {
    excel += `${criterion.name},${criterion.weight}\n`;
  });
  
  excel += '\n\nDETAILED SCORING\n';
  excel += 'Option,' + decision.criteria.map(c => c.name).join(',') + ',Total Score\n';
  results.forEach(result => {
    const scores = result.scores.map(s => s.score).join(',');
    excel += `${result.optionName},${scores},${result.totalScore.toFixed(2)}\n`;
  });
  
  return excel;
}

// Mobile-aware export function
export function exportDecision(decision: Decision, results: AnalysisResult[], format: 'json' | 'csv' | 'pdf' | 'excel', isMobile: boolean = false) {
  const timestamp = new Date().getTime();
  const baseName = decision.name.toLowerCase().replace(/\s+/g, '-');
  
  switch (format) {
    case 'json':
      const jsonContent = exportAsJSON(decision, results);
      downloadFile(jsonContent, `decision-data-${baseName}-${timestamp}.json`, 'application/json');
      break;
      
    case 'csv':
      const csvContent = exportAsCSV(decision, results);
      downloadFile(csvContent, `decision-data-${baseName}-${timestamp}.csv`, 'text/csv');
      break;
      
    case 'pdf':
      // Generate enhanced PDF-ready HTML
      const pdfContent = generatePDFContent(decision, results);
      const newWindow = window.open();
      if (newWindow) {
        newWindow.document.write(pdfContent);
        newWindow.document.close();
        // Auto-trigger print dialog for PDF save
        setTimeout(() => {
          newWindow.print();
        }, 500);
      }
      break;
      
    case 'excel':
      const excelContent = generateExcelContent(decision, results);
      downloadFile(excelContent, `decision-analysis-${baseName}-${timestamp}.csv`, 'text/csv');
      break;
  }
}
